### ISSUE TITLE
RuntimeError: unexpected status code (500) received; expected 200

### ISSUE THREAD

**Issue by rocket-turtle** [phrase/phraseapp-ruby#34]
We started using `phraseapp-ruby (1.6.0)` through `phraseapp-in-context-editor-ruby (1.2.1)` .
We try to translate `activerecord.models.org_units/location` and get an `status code (500)`.

Fast Setup with `PhraseApp::InContextEditor` but could be done without:
```
api_client = PhraseApp::InContextEditor.api_client
project_id = PhraseApp::InContextEditor.project_id
```

**Working query**
```
prefix = 'activerecord.models.org_unit'
# => "activerecord.models.org_unit"
params = PhraseApp::RequestParams::KeysSearchParams.new(q: "#{prefix}*")
=> #<PhraseApp::RequestParams::KeysSearchParams q="activerecord.models.org_unit*">

api_client.keys_search(project_id, 1, 100, params)
# => [[
# <PhraseApp::ResponseObjects::TranslationKey id="121", name="activerecord.models.org_unit", description=nil,
# name_hash="HASH", plural=true, tags=[...], created_at=Tue, 12 Dec 2017 13:34:08 +0000, updated_at=Tue, 12 Dec 2017 13:34:08 +0000>,
# <PhraseApp::ResponseObjects::TranslationKey id="834", name="activerecord.models.org_units/region", description=nil,
# name_hash="HASH", plural=true, tags=[...], created_at=Tue, 12 Dec 2017 13:35:08 +0000, updated_at=Tue, 12 Dec 2017 13:35:08 +0000>,
# <PhraseApp::ResponseObjects::TranslationKey id="295", name="activerecord.models.org_units/location", description=nil,
# name_hash="HASH", plural=true, tags=[...], created_at=Tue, 12 Dec 2017 13:34:08 +0000, updated_at=Tue, 12 Dec 2017 13:34:08 +0000>
# ...
# ], nil]
```

**Not working query**
```
prefix = 'activerecord.models.org_units/location'
# => "activerecord.models.org_units/location"
params = PhraseApp::RequestParams::KeysSearchParams.new(q: "#{prefix}*")
# => #<PhraseApp::RequestParams::KeysSearchParams q="activerecord.models.org_units/location*">

api_client.keys_search(project_id, 1, 100, params)
# RuntimeError: unexpected status code (500) received; expected 200
# 	from /Users/jos/.rvm/gems/ruby-2.2.8@mhmr/gems/phraseapp-ruby-1.6.0/lib/phraseapp-ruby/request_handler.rb:163:in `handleResponseStatus'
# 	from /Users/jos/.rvm/gems/ruby-2.2.8@mhmr/gems/phraseapp-ruby-1.6.0/lib/phraseapp-ruby/request_handler.rb:145:in `http_send'
# 	from /Users/jos/.rvm/gems/ruby-2.2.8@mhmr/gems/phraseapp-ruby-1.6.0/lib/phraseapp-ruby/request_handler.rb:103:in `send_request'
# 	from /Users/jos/.rvm/gems/ruby-2.2.8@mhmr/gems/phraseapp-ruby-1.6.0/lib/phraseapp-ruby/request_handler.rb:80:in `send_request_paginated'
# 	from /Users/jos/.rvm/gems/ruby-2.2.8@mhmr/gems/phraseapp-ruby-1.6.0/lib/phraseapp-ruby.rb:4240:in `keys_search'

# => #<Net::HTTPInternalServerError 500 Internal Server Error readbody=true>
```

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phraseapp-ruby) and we can take more direct action toward finding a solution.
