### ISSUE TITLE
Error when using branch_show to find a branch by id

### ISSUE THREAD

**Issue by andi-dev** [phrase/phraseapp-ruby#41]
When I am trying to find a branch by its id using the clients 'branch_show' message, I am running into the following error:

```
NoMethodError: undefined method `each_pair' for #<Array:0x00007f82c925fd48>
Did you mean?  each_slice
/usr/local/bundle/bundler/gems/phraseapp-ruby-2fc619ddfa86/lib/phraseapp-ruby.rb:107:in `initialize'
/usr/local/bundle/bundler/gems/phraseapp-ruby-2fc619ddfa86/lib/phraseapp-ruby.rb:3799:in `new'
/usr/local/bundle/bundler/gems/phraseapp-ruby-2fc619ddfa86/lib/phraseapp-ruby.rb:3799:in `branch_show'
```

I suspect that in https://github.com/phrase/phraseapp-ruby/blob/master/lib/phraseapp-ruby.rb#L3799 `rc.body` is an array.

**Comment by theSoenke** [comment]
Hi @andi-dev, thanks for reporting it. I will look into this

**Comment by theSoenke** [comment]
Could you maybe share the code snippet you are using to show the branch? I've tried it with a simple example which worked for me:

```
rsp, err = client.branch_show(PROJECT_ID, "branchName")
puts rsp
```

The API should also not return an Array for this endpoint

**Comment by andi-dev** [comment]
Hi @theSoenke and thanks for looking into it. I double checked my code, and discovered my mistake.
The api-docs describe the endpoint as `GET /api/v2/projects/:project_id/branches/:id`, so I assumed that branches have an 'id' field and did something like `client.branch_show(PROJECT_ID, previously_created_branch.id)`, while I would have needed to call `previously_created_branch.name`.

However my mistake was somewhat disguised by phraseapp-ruby's ResponseObjects being OpenStructs, so they do not raise an exception when calling a non-existing method / attribute. 

I think you can close this issue as the mistake was mine, but I think it would be a big improvement if you would use Structs instead of OpenStruct - and maybe if you anyway auto-generate this gem from an api specification it wouldn't be that much extra work.

Maybe the api could also raise a more meaningful error when passing nil as the branch-name / id.
Here is the simplified code to reproduce:

````
irb(main):027:0> client.branch_show(ENV['PHRASEAPP_PROJECT_ID'], nil)
NoMethodError: undefined method `each_pair' for #<Array:0x00007f602ce0acc0>
	from /usr/local/lib/ruby/2.3.0/ostruct.rb:101:in `initialize'
```

Thank you!
