### ISSUE TITLE
How to upload a YAML file?

### ISSUE THREAD

**Issue by yob** [phrase/phraseapp-ruby#6]
Hi,

I'm attempting to upload a YAML file with version `1.0.18` and getting a 500 error.

Here's the file:

```yaml
en:
  foo:
    bar: "hi"
```

Here's the code:

```ruby
params = PhraseApp::RequestParams::LocaleFileImportParams.new(
  file: "tmp/test.yml",
  file_format: "yml",
  tags:  "testing",
  skip_upload_tags: "true",
  update_translations: "true",
)
res = PhraseApp::Client.upload_create(@project_id, params)
```

Here's the exception:

```ruby
RuntimeError: unexpected status code (500) received; expected 201
        from /home/jh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/phraseapp-ruby-1.0.18/lib/request_handler.rb:173:in `handleResponseStatus'
        from /home/jh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/phraseapp-ruby-1.0.18/lib/request_handler.rb:146:in `send'
        from /home/jh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/phraseapp-ruby-1.0.18/lib/request_handler.rb:103:in `send_request'
        from /home/jh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/phraseapp-ruby-1.0.18/lib/phraseapp-ruby.rb:3695:in `upload_create'
```

Here's the body submitted with the POST:

```
--{PHRASE!!EOF}
Content-Disposition: form-data; name="file"; filename="test.yml"
Content-Type: text/plain

en:
  foo:
    bar: "hi"

--{PHRASE!!EOF}
Content-Disposition: form-data; name="file_format"

yml
--{PHRASE!!EOF}
Content-Disposition: form-data; name="skip_upload_tags"

true
--{PHRASE!!EOF}
Content-Disposition: form-data; name="tags"

testing
--{PHRASE!!EOF}
Content-Disposition: form-data; name="update_translations"

true
--{PHRASE!!EOF}--
```

**Comment by kevvvvv** [comment]
Hi @yob - thank you for reporting this. I investigated the issue. 

It is caused by a faulty Multipart request ("tags" should be a array e.g. "tags[]"). I will fix this shortly.

**Comment by kevvvvv** [comment]
Hi @yob - in the latest release, version 1.0.20, the behaviour i mentioned above is fixed.

However, tags should be supplied as an array. So slightly modifying your initial code:

```ruby
params = PhraseApp::RequestParams::LocaleFileImportParams.new(
  file: "tmp/test.yml",
  file_format: "yml",
  tags:  ["testing"],
  skip_upload_tags: "true",
  update_translations: "true",
)
res = PhraseApp::Client.upload_create(@project_id, params)
```

Again, thanks for pointing this out.
